Trivy fixes
common-fate/terraform-aws-common-fate-deployment pull request #22
Opened 2024-02-01 03:45 UTC by meyerjrr

2024-02-02 08:26 UTC, JoshuaWilkes requested changes
There were some typos and I have requested that we revert all the environment variable changes on the control plane because as far as I know they didn't fix the issue we were facing

2024-02-02 08:26 UTC, JoshuaWilkes commented on examples/full/main.tf
> +  alb_security_group_arn              = module.alb.alb_security_group_id
variable should be named id not arn
```suggestion
  alb_security_group_id             = module.alb.alb_security_group_id
```

2024-02-02 08:26 UTC, JoshuaWilkes commented on modules/aws-idc-integration/iam-roles/main.tf
> +        "Resource" : "*" #var.controlplane_task_role_arn
```suggestion
        "Resource" : "*"
```

2024-02-02 08:26 UTC, JoshuaWilkes commented on modules/aws-idc-integration/iam-roles/main.tf
> +        "Resource" : "*" # var.common_fate_aws_provisioner_role_arn
```suggestion
        "Resource" : "*"
```

2024-02-02 08:26 UTC, JoshuaWilkes commented on modules/aws-idc-integration/iam-roles/variables.tf
> +variable "controlplane_task_role_arn" {
This can be removed as it is unused
```suggestion

```

2024-02-02 08:26 UTC, JoshuaWilkes commented on modules/controlplane/main.tf
> +  container_definitions_secrets = concat(
I think that we revert this change given that it didn't solve the issue

I think it makes it harder to read in this context

2024-02-02 08:26 UTC, JoshuaWilkes commented on modules/controlplane/main.tf
> +          value = var.scim_source
Why has the order of all of these changes?
Did it make a difference?
It looks like this has been changed to the wrong value so I suggest that we revert all the environment variable changes in this file

```suggestion
          value = var.scim_source <-- this is incorrect
```

2024-02-02 08:26 UTC, JoshuaWilkes commented on examples/full/main.tf
> +  alb_security_group_arn = module.alb.alb_security_group_id
```suggestion
  alb_security_group_id = module.alb.alb_security_group_id
```

2024-02-02 08:26 UTC, JoshuaWilkes commented on examples/full/main.tf
> +  alb_security_group_arn = module.alb.alb_security_group_id
```suggestion
  alb_security_group_id = module.alb.alb_security_group_id
```

2024-02-02 09:20 UTC, chrnorm commented on modules/database/main.tf
> +  storage_encrypted            = true
we will need to confirm in our internal deploy if these changes cause database downtime

2024-02-06 04:11 UTC, JoshuaWilkes approved these changes

2024-02-06 04:11 UTC, merged