Josh/cf 2701 create the stackset process for deploying required iam roles
common-fate/terraform-aws-common-fate-deployment pull request #47
Opened 2024-02-12 06:54 UTC by JoshuaWilkes

2024-02-12 14:48 UTC, chrnorm requested changes

2024-02-12 14:48 UTC, chrnorm commented on modules/aws-idc-integration/audit-roles/variables.tf
> +}
We should switch this to just a `string` - because the IAM roles are global, they should only be deployed to a single region

2024-02-12 14:50 UTC, chrnorm requested changes

2024-02-12 14:50 UTC, chrnorm commented on modules/aws-rds-integration/iam-roles/iam-roles.yaml
> +  CF::Template: AWSAudit
These are intended to be used as metadata allowing us to introspect our own templates in the customer environment - the `CF::Template` field should be globally unique. We're already using `AWSAudit` on the audit role template, so we should name this something else

```suggestion
  CF::Template: AWSRDSProvisioner
```

2024-02-13 07:42 UTC, JoshuaWilkes commented on modules/aws-idc-integration/audit-roles/main.tf
> +  deployment_targets {
We need to make the concurrency limits higher by default and expose a variable for configuring it.

by default I think it deployed 1 stack at a time which is awful

2024-02-16 02:26 UTC, merged